#-------------------- guisheng ------------------------
guisheng:
    build: .
    env_file:
        - guisheng.env
    command: gunicorn --name guisheng -b 0.0.0.0:8888 -w 2 wsgi:app
    ports:
        - "8888:8888"
    links:
        - redis1
        - redis2

#------------------- celery ---------------------------
celery:
    build: .
    env_file:
        - guisheng.env
    command: celery worker -A guisheng_app.workers.hottag.celery --loglevel=INFO
    links:
        - redis1
        - redis2

#------------------- celery beats----------------------
celery_beats:
    build: .
    env_file:
        - guisheng.env
    command: celery -A guisheng_app.workers.hottag.celery beat --loglevel=INFO
    links:
        - redis1
        - redis2

#------------------ redis ----------------------------
redis1:     #储存热门搜索
    image: redis
    command: redis-server --port 6380
    ports:
        - "6380:6380"

redis2:     # celery/celery-beat
    image: redis
    command: redis-server --port 6381
    ports:
        - "6381:6381"
